version: '2'
services:
 
  mysql:
   container_name: mysql
   image: mysql-petclinic:latest
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /home/victor/.m2:/root/.m2
    ports:
       - "8080:8080"
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
